import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const flowerIsland = localFont({
  src: "./fonts/MapoFlowerIslandA.woff",
  variable: "--font-flower-island",
  weight: "100 900",
});
const kopubBatang = localFont({
  src: "./fonts/KoPubWorld-Batang-Medium.woff2",
  variable: "--font-kopub-batang",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${flowerIsland.variable} ${kopubBatang.variable} antialiased`}
      >
        <div className="bg-stars-img flex-center full-size">{children}</div>
      </body>
    </html>
  );
}
